Repository LunarVim/lunarvim.org, pull requests merged in 2022-10, with the labels that each got.

#235 easter egg
  docs/02-installation.md
Labels: HACKTOBERFEST-ACCEPTED

#229 mobile layout column order, color adjustmnet, 1px edge fix
  src/components/Preview/styles.module.css
  src/css/custom.css
  src/pages/index.jsx
  src/pages/index.module.css
Labels: HACKTOBERFEST-ACCEPTED

#230 i18n setup + example
  docusaurus.config.js
  i18n/de/code.json
  i18n/de/docusaurus-plugin-content-blog/options.json
  i18n/de/docusaurus-plugin-content-docs/current.json
  i18n/de/docusaurus-plugin-content-docs/current/01-introduction.md
  i18n/de/docusaurus-theme-classic/navbar.json
  src/components/Preview/index.jsx
  src/pages/index.jsx
Labels: HACKTOBERFEST-ACCEPTED

#243 docs: add tutorial to installation and color scheme section
  docs/01-installation.md
  docs/configuration/03-colorschemes.md
Labels: documentation

#248 ⌨️: slogan typewriter animation
  docusaurus.config.js
  src/components/Hero/Slogan.jsx
  src/components/Hero/index.jsx
  src/components/Hero/index.module.css
Labels: HACKTOBERFEST-ACCEPTED

#264 fix: all invalid admonitions
  docs/languages/README.md
  docs/plugins/README.md
Labels: HACKTOBERFEST-ACCEPTED

#275 embed youtube video/videos/playlist to docs where appropriate
  docs/02-quick-start.md
  docs/configuration/01-settings.md
  docs/configuration/02-keybindings.md
  docs/configuration/04-nerd-fonts.md
Labels: hacktoberfest
